#!/usr/bin/ruby
require 'fileutils'

lines=`otool -L #{ARGV[0]}`.split "\n"
lines.shift #lose intro line

FileUtils.chmod 0744, ARGV[0]

if ARGV[0] =~ /\.(dylib|resolver)$/
  `install_name_tool -id @executable_path/#{ARGV[0]} #{ARGV[0]}`
  lines.shift
end

lines.each do |dylib|
  dylib=dylib.strip.split[0]
  `install_name_tool -change #{dylib} @executable_path/#{File.basename dylib} #{ARGV[0]}` unless dylib =~ %r[^/usr/lib] or dylib =~ %r[^/System]
end
